/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.MenuPrincipalView;
import ui.FacturaView;
import database.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.FallaService;

/**
 *
 * @author MrsHo
 */
public class VentasView extends javax.swing.JFrame {
    public void cargarProductos() {
    try {
        Connection conn = Conexion.conectar();
        String sql = "SELECT * FROM productos";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        cbProductos.removeAllItems(); // 👈 IMPORTANTE

        while (rs.next()) {
            cbProductos.addItem(rs.getInt("id") + " - " + rs.getString("nombre"));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    public void configurarTabla() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Precio");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Subtotal");

    tablaVenta.setModel(modelo);
}
    public void calcularTotal() {
    double total = 0;

    for (int i = 0; i < tablaVenta.getRowCount(); i++) {
        total += Double.parseDouble(tablaVenta.getValueAt(i, 4).toString());
    }

    lblTotal.setText("Total: " + total);
}
    private double obtenerTotal() {
    double total = 0;

    for (int i = 0; i < tablaVenta.getRowCount(); i++) {
        total += Double.parseDouble(tablaVenta.getValueAt(i, 4).toString());
    }

    return total;
}
    private String generarFactura() {

    StringBuilder sb = new StringBuilder();

    sb.append("=========== FACTURA ===========\n");
    sb.append("        MI NEGOCIO\n");
    sb.append("Fecha: ").append(java.time.LocalDateTime.now()).append("\n");
    sb.append("--------------------------------\n");

    double total = 0;

    for (int i = 0; i < tablaVenta.getRowCount(); i++) {

        String nombre = tablaVenta.getValueAt(i, 1).toString();
        int cantidad = Integer.parseInt(tablaVenta.getValueAt(i, 3).toString());
        double subtotal = Double.parseDouble(tablaVenta.getValueAt(i, 4).toString());

        total += subtotal;

        sb.append(nombre)
          .append("  x").append(cantidad)
          .append("  = ").append(String.format("%.2f", subtotal))
          .append("\n");
    }

    sb.append("--------------------------------\n");
    sb.append("TOTAL: ").append(String.format("%.2f", total)).append("\n");
    sb.append("================================\n");

    return sb.toString();
}
    /**
     * Creates new form VentasView
     */
    public VentasView() {
       
    initComponents();
    configurarTabla();
    cargarProductos(); // 👈 SI NO ESTÁ, no funciona

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbProductos = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductosActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVenta);

        lblTotal.setText("Total");

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnAtras.setText("Volver");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotal)
                        .addComponent(btnAgregar)
                        .addComponent(btnVender)
                        .addComponent(btnQuitar))
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(1, 1, 1)
                        .addComponent(btnVender))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProductosActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed

    if (tablaVenta.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay productos en la venta");
        return;
    }

    int opcion = JOptionPane.showConfirmDialog(this, "Confirmar venta?", "Venta", JOptionPane.YES_NO_OPTION);
    if (opcion != JOptionPane.YES_OPTION) return;

    Connection conn = null;

    try {
        conn = Conexion.conectar();
        conn.setAutoCommit(false);

        // 1. Insertar venta
        String sqlVenta = "INSERT INTO ventas(fecha, total) VALUES (NOW(), ?)";
        PreparedStatement psVenta = conn.prepareStatement(sqlVenta, Statement.RETURN_GENERATED_KEYS);

        double total = obtenerTotal();
        psVenta.setDouble(1, total);
        psVenta.executeUpdate();

        ResultSet rs = psVenta.getGeneratedKeys();

        if (!rs.next()) {
            throw new Exception("No se pudo obtener ID de venta");
        }

        int idVenta = rs.getInt(1);

        // 2. Procesar productos
        for (int i = 0; i < tablaVenta.getRowCount(); i++) {

            int idProducto = Integer.parseInt(tablaVenta.getValueAt(i, 0).toString());
            int cantidad = Integer.parseInt(tablaVenta.getValueAt(i, 3).toString());

            // validar stock
            String checkStock = "SELECT stock FROM productos WHERE id=?";
            PreparedStatement psCheck = conn.prepareStatement(checkStock);
            psCheck.setInt(1, idProducto);

            ResultSet rsStock = psCheck.executeQuery();

            if (rsStock.next()) {
                int stockActual = rsStock.getInt("stock");

                if (cantidad > stockActual) {
                    throw new Exception("Stock insuficiente (ID " + idProducto + ")");
                }
            }

            // detalle
            String sqlDetalle = "INSERT INTO detalle_venta(id_venta, id_producto, cantidad) VALUES (?, ?, ?)";
            PreparedStatement psDetalle = conn.prepareStatement(sqlDetalle);

            psDetalle.setInt(1, idVenta);
            psDetalle.setInt(2, idProducto);
            psDetalle.setInt(3, cantidad);
            psDetalle.executeUpdate();

            // actualizar stock
            String sqlStock = "UPDATE productos SET stock = stock - ? WHERE id=?";
            PreparedStatement psStock = conn.prepareStatement(sqlStock);

            psStock.setInt(1, cantidad);
            psStock.setInt(2, idProducto);
            psStock.executeUpdate();
        }

        conn.commit();

        JOptionPane.showMessageDialog(this, "Venta realizada correctamente");

        // ✅ FACTURA
        String factura = generarFactura();
        FacturaView f = new FacturaView(factura);
        f.setLocationRelativeTo(null);
        f.setVisible(true);

        // limpiar
        ((DefaultTableModel) tablaVenta.getModel()).setRowCount(0);
        lblTotal.setText("Total: 0");

    } catch (Exception e) {

        try {
            if (conn != null) conn.rollback();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        JOptionPane.showMessageDialog(this, "Error en la venta: " + e.getMessage());

        FallaService.registrar("VENTA FALLIDA → " + e.getMessage());

    } finally {
        try {
            if (conn != null) {
                conn.setAutoCommit(true);
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
                                      
    if (cbProductos.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
    }

    if (txtCantidad.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese cantidad");
        return;
    }

    int cantidad;

    try {
        cantidad = Integer.parseInt(txtCantidad.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cantidad inválida");
        return;
    }

    if (cantidad <= 0) {
        JOptionPane.showMessageDialog(this, "Cantidad inválida");
        return;
    }

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        String item = cbProductos.getSelectedItem().toString();
        int id = Integer.parseInt(item.split(" - ")[0]);

        conn = Conexion.conectar();
        String sql = "SELECT * FROM productos WHERE id=?";
        ps = conn.prepareStatement(sql);
        ps.setInt(1, id);

        rs = ps.executeQuery();

        if (rs.next()) {

            String nombre = rs.getString("nombre");
            double precio = rs.getDouble("precio");
            int stock = rs.getInt("stock");

            DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();

            boolean existe = false;

            for (int i = 0; i < modelo.getRowCount(); i++) {

                int idTabla = Integer.parseInt(modelo.getValueAt(i, 0).toString());

                if (idTabla == id) {

                    int cantidadActual = Integer.parseInt(modelo.getValueAt(i, 3).toString());
                    int nuevaCantidad = cantidadActual + cantidad;

                    // 🔒 VALIDAR STOCK ACUMULADO
                    if (nuevaCantidad > stock) {
                        JOptionPane.showMessageDialog(this, "Stock insuficiente");

                        FallaService.registrar(
                            "Stock insuficiente acumulado | ID: " + id +
                            " | Intento: " + nuevaCantidad +
                            " | Stock: " + stock
                        );

                        return;
                    }

                    modelo.setValueAt(nuevaCantidad, i, 3);
                    modelo.setValueAt(precio * nuevaCantidad, i, 4);

                    existe = true;
                    break;
                }
            }

            // 🔥 VALIDACIÓN CUANDO ES NUEVO (AQUÍ FALTABA)
            if (!existe) {

                if (cantidad > stock) {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente");

                    FallaService.registrar(
                        "Stock insuficiente nuevo | ID: " + id +
                        " | Cantidad: " + cantidad +
                        " | Stock: " + stock
                    );

                    return;
                }

                modelo.addRow(new Object[]{id, nombre, precio, cantidad, precio * cantidad});
            }

            calcularTotal();
            txtCantidad.setText("");
        }

    } catch (Exception e) {

        FallaService.registrar("Error en agregar producto: " + e.getMessage());
        e.printStackTrace();

    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed


    int fila = tablaVenta.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
    modelo.removeRow(fila);

    calcularTotal();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    MenuPrincipalView menu = new MenuPrincipalView();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
